// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"wxxb789/code-snippets/golang/project-template/internal/biz"
	"wxxb789/code-snippets/golang/project-template/internal/data"
	"wxxb789/code-snippets/golang/project-template/internal/service"
)

// Injectors from wire.go:

func InitializeService() *service.UserService {
	db := data.NewDB()
	userRepoImpl := data.NewUserRepoImpl(db)
	userBiz := biz.NewUserBiz(userRepoImpl)
	userService := service.NewUserService(userBiz)
	return userService
}
